######## Stellar info ########
stellar:
  version: '1.7.0'
  homepage: 'https://xaoxuu.com/wiki/stellar/'
  repo: 'https://github.com/xaoxuu/hexo-theme-stellar'
  cdn_css: # Use cdn links instead of /css/main.css
  cdn_js: # Use cdn links instead of /js/main.js


######## head tags ########
open_graph:
  enable: true
  github_id: ivitan


######## Sidebar ########
sidebar:
  logo:
    avatar: '[https://cdn.jsdelivr.net/gh/ivitan/Picture@master/images/ivitan.png](/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  menu:
    post: '[主页](/)'
    wiki: '[项目](/wiki/)'
    about: '[关于](/about/)'
  # Sidebar widgets
  widget_layout:
    index: recent # for home/wiki/categories/tags/archives/404 pages
    page: toc # for pages using 'layout:page'
    post: [toc, repo_info] # for pages using 'layout:post'
    wiki: [toc, repo_info, wiki_more] # for pages using 'layout:wiki'
  widgets:
    # Recent update
    recent:
      layout: recent
      rss: /xml/atom.xml # npm i hexo-generator-feed
      limit: 10 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
      fallback: recent # Use a backup widget when toc does not exist.

######## Main ########
breadcrumb:
  home: home # config.title / config.author / home or custom content

######## Article ########
article:
  # 如果没有指定封面，是否根据 tags 作为关键词搜索封面？
  auto_cover: false # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 200
  # 分类颜色
  category_color:
    '新闻稿': '#DA0F47'
  # 文章许可协议
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议'
  # 分享
  share: # [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: false
    max_count: 5
    auto_cover: true # 如果没有封面就根据 tags 作为关键词搜索封面，开了此项将不会自动从文章中提取首张图片作为封面了。



######## Comments ########
comments:
  service: valine # beaudar, utterances, valine, twikoo
  valine:
    js: https://cdn.jsdelivr.net/gh/XuxuGood/simple-blog-cdn@main/js/Valine.min.js
    appId: D33WPBHpBw2CjwdWpFvpUhDm-MdYXbMMI
    appKey: MzQtKvSeVPU4nS4ljd3zlbMp
    placeholder:
    requiredFields: [nick, mail]
    enableQQ: true # Unstable avatar link
    recordIP: false # Record commenter IP
    avatar: robohash # gravatar style https://valine.js.org/avatar
    pageSize: 10 # comment list page size
    lang: zh-cn
    highlight: true
    mathJax: false
    tagMeta: [博主, 小伙伴, 访客] # 标签要显示的文字,默认'博主,小伙伴,访客'
    metaPlaceholder:
      nick: "昵称/QQ号(必填)"
      mail: "邮箱（必填，完全保密）"
      link: "网址(https://)"
    master: #md5加密后的博主邮箱
      - 6783037F2DF30EAB99F9FC256157D875
    friends: #md5加密后的小伙伴邮箱
      - 6783037F2DF30EAB99F9FC256157D875

######## Footer ########
footer:
  social:
    github:
      icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/ivitan
    # music:
    #   icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3845874.svg"/>'
    #   url: /
    # unsplash:
    #   icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3616429.svg"/>'
    #   url: /
    # comments:
    #   icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/942ebbf1a4b91.svg"/>'
    #   url: /about/#comments
  sitemap:
    # '博客':
    #   - '[近期](/)'
    #   - '[分类](/)'
    #   - '[标签](/)'
    #   - '[归档](/)'
    # '项目':
    #   - '[开源库](/)'
    # '社交':
    #   - '[友链](/)'
    #   - '[留言板](/)'
    # '更多':
    #   - '[关于本站](/)'
    #   - '[GitHub](/)'
  license: '[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)'
  source: #'[GitHub](https://github.com/xaoxuu/hexo-theme-stellar)'
  more: # string or array (support markdown)


######## Tag Plugins ########
tag_plugins:
  # {% note text %}
  note:
    default_color: '' # light, dark, red, orange, yellow, green, cyan, blue, purple
  # {% checkbox %}
  checkbox:
    interactive: false # enable interactive for user
  # {% quot %}
  quot:
    default: # 可以自行配置多种图标方案
      prefix: https://s2.loli.net/2022/01/04/vsTB5pGrIHfPxSj.png
      suffix: https://s2.loli.net/2022/01/04/NORdtjlAhifZSns.png
    hashtag:
      prefix: https://s2.loli.net/2022/01/04/UvHcsa73jQPnobq.png
  # {% emoji %}
  emoji:
    default: https://cdn.jsdelivr.net/gh/volantis-x/cdn-emoji/qq/%s.gif
    twemoji: https://cdn.jsdelivr.net/gh/twitter/twemoji/assets/svg/%s.svg
    qq: https://cdn.jsdelivr.net/gh/volantis-x/cdn-emoji/qq/%s.gif
    aru: https://cdn.jsdelivr.net/gh/volantis-x/cdn-emoji/aru-l/%s.gif
    tieba: https://cdn.jsdelivr.net/gh/volantis-x/cdn-emoji/tieba/%s.png
  # {% image %}
  image:
    fancybox: # true, false


######## JS Plugins ########
plugins:
  ## required plugins ##
  # jquery
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js

  # issues api
  sitesjs: /js/plugins/sites.js
  friendsjs: /js/plugins/friends.js

  ## optional plugins ##
  # preload
  preload:
    enable: true
    service: flying_pages # instant_page, flying_pages
    instant_page: https://cdn.jsdelivr.net/gh/volantis-x/cdn-volantis@4.1.2/js/instant_page.js
    flying_pages: https://cdn.jsdelivr.net/gh/gijo-varghese/flying-pages@2.1.2/flying-pages.min.js

  # image lazyload
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: true # [hexo clean && hexo s] is required after changing this value.
    js: https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js
    transition: blur # blur, fade

  # https://scrollrevealjs.org/api/reveal.html
  scrollreveal:
    enable: #true
    js: https://cdn.jsdelivr.net/npm/scrollreveal@4.0.9/dist/scrollreveal.min.js
    distance: 8px
    duration: 500 # ms
    interval: 100 # ms
    scale: 1 # 0.1~1

  # https://fancyapps.com/docs/ui/fancybox/
  # available for {% image xxx %}
  fancybox:
    enable: true
    js: https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js
    css: https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.css
    # 可以处理评论区的图片（不支持 iframe 类评论系统）例如：
    # 使用valine评论可以写: .vcontent img:not(.vemoji)
    # 使用twikoo评论可以写: .tk-content img:not([class*="emo"])
    selector: .swiper-slide img # 多个选择器用英文逗号隔开

  # swiper
  swiper:
    enable: true
    css: https://unpkg.com/swiper@6/swiper-bundle.min.css
    js: https://unpkg.com/swiper@6/swiper-bundle.min.js


  # 赫蹏 (Heti) - 专为中文网页内容设计的排版样式增强
  # https://github.com/sivan/heti
  heti:
    enable: false
    css: https://unpkg.com/heti/umd/heti.min.css
    js: https://unpkg.com/heti/umd/heti-addon.min.js


style:
  darkmode: auto # auto / always / false
  theme:
    light: '#f8f8f8'
    dark: '#232222'
  animated_avatar:
    animate: auto # auto, always
    background: https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.2/avatar/round/rainbow64@3x.webp
  codeblock:
    scrollbar: 4px

default:
  avatar: https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/avatar/round/3442075.svg
  link: https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/link/8f277b4ee0ecd.svg
  cover: https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/cover/76b86c0226ffd.svg
  image: https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/image/2659360.svg
